# Generated by Django 6.0.3 on 2026-04-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewApp', '0002_category_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
